"""Databricks MCP Server - FastMCP-based tools for Databricks operations."""

__version__ = "0.1.0"

# All tool names registered by this server.
# Import this (not server.py) when you only need names — avoids triggering
# tool registrations and Databricks SDK imports.
TOOL_NAMES: list[str] = [
    "ask_genie",
    "ask_genie_followup",
    "cancel_run",
    "create_job",
    "create_or_update_dashboard",
    "create_or_update_genie",
    "create_or_update_ka",
    "create_or_update_mas",
    "create_or_update_pipeline",
    "create_pipeline",
    "create_volume_directory",
    "delete_genie",
    "delete_job",
    "delete_ka",
    "delete_mas",
    "delete_pipeline",
    "delete_volume_directory",
    "delete_volume_file",
    "download_from_volume",
    "execute_databricks_command",
    "execute_sql",
    "execute_sql_multi",
    "find_job_by_name",
    "find_ka_by_name",
    "find_mas_by_name",
    "find_pipeline_by_name",
    "get_best_cluster",
    "get_best_warehouse",
    "get_dashboard",
    "get_genie",
    "get_job",
    "get_ka",
    "get_mas",
    "get_pipeline",
    "get_pipeline_events",
    "get_run",
    "get_run_output",
    "get_serving_endpoint_status",
    "get_table_details",
    "get_update",
    "get_volume_file_info",
    "list_clusters",
    "list_dashboards",
    "list_genie",
    "list_jobs",
    "list_runs",
    "list_serving_endpoints",
    "list_volume_files",
    "list_warehouses",
    "manage_uc_connections",
    "manage_uc_grants",
    "manage_uc_monitors",
    "manage_uc_objects",
    "manage_uc_security_policies",
    "manage_uc_sharing",
    "manage_uc_storage",
    "manage_uc_tags",
    "publish_dashboard",
    "query_serving_endpoint",
    "run_job_now",
    "run_python_file_on_databricks",
    "start_update",
    "stop_pipeline",
    "trash_dashboard",
    "unpublish_dashboard",
    "update_job",
    "update_pipeline",
    "upload_file",
    "upload_folder",
    "upload_to_volume",
    "wait_for_run",
]
