"""Default APX REST router — generated by `apx init`, unchanged for this example."""

from .core import Dependencies, create_router

router = create_router()


@router.get("/health", operation_id="health")
async def health() -> dict:
    return {"status": "ok"}
