"""hubspot-complaints-agent — summarizes HubSpot ticket complaints from Unity Catalog.

Generated by ``apx-agent scaffold hubspot-complaints-agent --target apps``,
then grounded on a synced HubSpot Tickets table. ``agent_server/start_server.py``
wraps this for the Databricks Apps runtime (chat); ``scripts/monthly_summary.py``
invokes the same ``agent`` object once a month via ``run_once`` (scheduled Job).
"""
from __future__ import annotations

import os

from apx_agent import DataAgent

# Defaults match the scaffold's baked placeholders (see the original
# `apx-agent scaffold ... --catalog placeholder_catalog --schema
# placeholder_schema` invocation) and this example's default table name.
_DEFAULT_CATALOG = "placeholder_catalog"
_DEFAULT_SCHEMA = "placeholder_schema"
_DEFAULT_TICKETS_TABLE = "tickets"

CATALOG = os.environ.get("APX_CATALOG", _DEFAULT_CATALOG)
SCHEMA = os.environ.get("APX_SCHEMA", _DEFAULT_SCHEMA)
TICKETS_TABLE = os.environ.get("APX_TICKETS_TABLE", _DEFAULT_TICKETS_TABLE)
TABLE = f"{CATALOG}.{SCHEMA}.{TICKETS_TABLE}"

agent = DataAgent(
    CATALOG, SCHEMA,
    name="hubspot-complaints-agent",
    knowledge="./.apx/okf",  # OKF bundle grounds the agent + populates the dev-UI Knowledge tab
    instructions=(
        f"You summarize customer complaints from HubSpot support tickets synced "
        f"into Unity Catalog. Query the fully-qualified table {TABLE}"
        "(hs_object_id, subject, content, hs_createdate, hs_pipeline_stage) with "
        "the SQL tool.\n\n"
        "A complaint's month is defined by hs_createdate (when the ticket was "
        "created), not when it was closed. To summarize a given month:\n"
        "  1. Query tickets WHERE CAST(date_trunc('month', hs_createdate) AS DATE) "
        "= that month's first day.\n"
        "  2. Report the total ticket count.\n"
        "  3. Read the subject/content text and group tickets into 3-6 recurring "
        "themes (e.g. 'billing confusion', 'shipping delays'), each with its "
        "count and 1-2 representative example subjects.\n"
        "  4. If asked to compare months, note the count trend (up/down/flat) "
        "versus the prior month.\n"
        "Base every number on the SQL tool's results — never estimate."
    ),
)
