"""samples-bakehouse — apx-agent root agent (ADK-style top-level definition).

Generated by ``apx-agent agents scaffold samples-bakehouse --target apps``.

Edit this file to define your agent. ``agent`` is the canonical top-level
symbol that ``agent_server/start_server.py`` imports + wraps for the
Databricks Apps runtime. The same symbol is consumed by
``apx-agent agents deploy --target model-serving`` if you also publish to a serving
endpoint.

The Apps runtime boilerplate — ``compile_to_responses_agent``,
``@invoke()`` / ``@stream()`` registration, MCP mounting — lives in
``agent_server/start_server.py`` so this file stays focused on the
agent's behavior.
"""
from __future__ import annotations

import os

from apx_agent import DataAgent

from apx_agent import Dependencies
from apx_agent.sql_tools import run_sql


def sample_media_customer_reviews(ws: Dependencies.Workspace) -> dict:
    """Preview a few rows of `samples.bakehouse.media_customer_reviews` — your first tool.

    Runs as the calling user, so Unity Catalog enforces *their* grants
    (auth passthrough — no token handling here). Add params + richer SQL
    to make it your own, or generate more tools on the Edit page.
    """
    return run_sql(ws, "SELECT * FROM `samples`.`bakehouse`.`media_customer_reviews` LIMIT 5")



# A governed data agent over ``samples.bakehouse`` (schema baked at scaffold
# time — no runtime discovery needed). It answers questions grounded in that
# schema and queries via a SQL tool that runs as the calling user.
#
# Make it your own:
#   * point it at your own data:  re-scaffold with --catalog/--schema
#   * re-scaffold to refresh the baked schema:  apx-agent agents scaffold <name> --catalog <c>
#   * add ``genie_space=...`` / ``vector_index=...`` for Genie or Vector Search
#   * or drop back to a plain ``Agent(tools=[...])`` with your own ``@tool``s
#
# APX_CATALOG/APX_SCHEMA (set per DAB target — see README "Promoting to
# another environment") override the scaffolded default below, so the same
# agent.py can run against a different catalog/schema per environment.
_CATALOG = "samples"
_SCHEMA = "bakehouse"

agent = DataAgent(
    os.environ.get("APX_CATALOG", _CATALOG),
    os.environ.get("APX_SCHEMA", _SCHEMA), extra_tools=[sample_media_customer_reviews],
    name="samples-bakehouse", knowledge="./.apx/okf",
)
