"""quickstart — one-shot setup for the entity_resolution_agent Apps deploy.

Run via ``uv run quickstart`` (registered as a console script in
``pyproject.toml``). Does the minimum needed before ``apx deploy --target apps``:

  1. Create (or reuse) an MLflow experiment at
     ``/Users/${USER}/entity-resolution-agent-${BUNDLE_TARGET}``.
  2. Write a local ``.env`` with the resolved ``MLFLOW_EXPERIMENT_ID``
     so the bundle and the agent module pick it up.

entity_resolution_agent uses ``InMemoryMemoryStore``, so there's no Lakebase
provisioning step. If you swap in ``LakebaseMemoryStore`` later, see
``docs/lakebase-recipe.md`` for the provisioning recipe.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


def _resolve_user() -> str:
    """Best-effort user identity for the experiment path."""
    for env_var in ("DATABRICKS_USER", "USER", "USERNAME"):
        v = os.environ.get(env_var)
        if v:
            return v
    return "unknown-user"


def _resolve_target() -> str:
    """Bundle target — defaults to 'dev' to match databricks.yml."""
    return os.environ.get("BUNDLE_TARGET", "dev")


def _ensure_experiment(path: str) -> str:
    """Create or reuse the MLflow experiment at ``path``; return its ID."""
    try:
        import mlflow
    except ImportError as e:
        raise SystemExit(
            "mlflow is required. Install with: uv sync"
        ) from e

    # Default to the Databricks tracking URI; users can override if running
    # against a local file:// MLflow.
    mlflow.set_tracking_uri(os.environ.get("MLFLOW_TRACKING_URI", "databricks"))

    client = mlflow.tracking.MlflowClient()
    existing = client.get_experiment_by_name(path)
    if existing is not None:
        print(f"  reuse  experiment {path} (id={existing.experiment_id})")
        return existing.experiment_id

    exp_id = client.create_experiment(path)
    print(f"  create experiment {path} (id={exp_id})")
    return exp_id


def _write_env(env_path: Path, experiment_id: str, experiment_path: str) -> None:
    """Write a minimal ``.env`` for local + bundle consumption."""
    lines = [
        "# Generated by scripts/quickstart.py — safe to regenerate.",
        f"MLFLOW_EXPERIMENT_ID={experiment_id}",
        f"MLFLOW_EXPERIMENT_NAME={experiment_path}",
        "MLFLOW_TRACKING_URI=databricks",
    ]
    env_path.write_text("\n".join(lines) + "\n")
    print(f"  write  {env_path}")


def main() -> int:
    user = _resolve_user()
    target = _resolve_target()
    experiment_path = f"/Users/{user}/entity-resolution-agent-{target}"

    experiment_id = _ensure_experiment(experiment_path)

    env_path = Path(__file__).resolve().parent.parent / ".env"
    _write_env(env_path, experiment_id, experiment_path)

    print()
    print("Quickstart complete.")
    print(f"  experiment : {experiment_path}")
    print(f"  experiment_id : {experiment_id}")
    print(f"  env file : {env_path}")
    print()
    print("Next: apx deploy --target apps")
    return 0


if __name__ == "__main__":
    sys.exit(main())
