"""FastAPI entry point for Databricks Apps — AUTO-GENERATED by apx-agent scaffold.

Don't edit this file. Edit ``../agent.py`` instead — that's where your
agent lives. This file wires it into the Databricks Apps runtime:

  * Imports your ``agent`` from the top-level ``agent.py``.
  * Compiles it to the MLflow ResponsesAgent contract.
  * Registers ``@invoke`` / ``@stream`` handlers.
  * Mounts apx-agent's ``/mcp`` + ``/.well-known/agent.json`` + ``/health``
    so Genie / Genie Code can consume the same agent.
  * Mounts ``/readyz`` — a capability self-test that proves the agent answers
    and traces (used by ``apx-agent deploy`` as a readiness gate).

Run via ``uvicorn agent_server.start_server:app --host 0.0.0.0 --port $DATABRICKS_APP_PORT``
(driven by ``databricks.yml`` on deploy).
"""

from __future__ import annotations

import os

from mlflow.genai.agent_server import AgentServer, invoke, stream

from apx_agent import compile_to_responses_agent, mount_mcp_endpoints, mount_readyz
from apx_agent._defaults import _make_workspace_client
from apx_agent._inspection import _load_agent_config
from apx_agent._memory_wiring import resolve_conversation_store
from apx_agent._mlflow_tracing import autolog_if_env
from apx_agent._wiring import finalize_agent

# Enable MLflow LangChain/LangGraph auto-tracing when APX_AGENT_MLFLOW_AUTOLOG
# is set (databricks.yml sets it on deploy). Must run before the agent's
# LangChain components are built/invoked.
autolog_if_env()

# Import the user's agent from the top-level module.
from agent import agent

# Default matches the model baked into pyproject.toml's [tool.apx.agent].model
# at scaffold time — see that file for the source of truth.
_DEFAULT_MODEL = "databricks-claude-sonnet-4-6"
MODEL = os.environ.get("APX_MODEL", _DEFAULT_MODEL)

_ws = _make_workspace_client()
# Load pyproject.toml config and fully finalize the agent so [tool.apx.agent]
# blocks (memory, session, tools, guardrails) are honoured on Apps deploy —
# not just when served via create_app().
_agent_config = _load_agent_config()
finalize_agent(agent, _agent_config, ws=_ws)
# Conversation store: config-driven (Delta/Lakebase via [tool.apx.agent].session)
# when declared; otherwise an in-process store so multi-turn threading and the
# dev UI History panel work out of the box. In-memory state resets on restart —
# declare a session block for durable history.
_conversation_store = resolve_conversation_store(_agent_config, _ws, agent=agent)
if _conversation_store is None:
    from apx_agent import InMemoryConversationStore
    _conversation_store = InMemoryConversationStore()
# agent_id must match the name the dev-UI History panel filters by
# (the pyproject [tool.apx.agent].name) or conversations stay invisible.
_invoke_fn, _stream_fn = compile_to_responses_agent(
    agent,
    model=MODEL,
    conversation_store=_conversation_store,
    agent_id=_agent_config.name if _agent_config else None,
)


# Async bridge: AgentServer calls sync handlers directly ON the event
# loop, so a slow tool would block every other request on the replica
# (other sessions, the dev UI, /health). These wrappers run the sync
# agent work on worker threads instead — see apx_agent._async_bridge.
from apx_agent import make_async_invoke, make_async_stream

non_streaming = invoke()(make_async_invoke(_invoke_fn))
streaming = stream()(make_async_stream(_stream_fn))


server = AgentServer(agent_type="ResponsesAgent")
app = server.app

mount_mcp_endpoints(app, agent)
mount_readyz(app, agent)

app.state.workspace_client = _ws
app.state.conversation_store = _conversation_store


if __name__ == "__main__":
    server.run("agent_server.start_server:app")
