/**
 * apx scaffold — generate a new agent project.
 *
 * TS port of the Python `_scaffold_apps` / `_scaffold_model_serving` flows.
 * Templates are inlined as static strings so the scaffold doesn't pull in
 * any runtime template engine — match the Python behavior exactly.
 *
 * Two `--target` modes:
 *
 *   * `model-serving` — flat agent.ts + app.ts layout. Deployed via the
 *     traditional Mosaic AI ChatAgent flow.
 *   * `apps` — Databricks Asset Bundle layout: `agent_server/` + `start.ts`
 *     entry running an Express server with `mountResponsesAgent`, plus
 *     `databricks.yml`. Deployed via `apx deploy --target apps`.
 */

import { mkdirSync, existsSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import type { Command } from 'commander';
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Template — model-serving target (kept tight; not the focus of this port)
// ---------------------------------------------------------------------------

const MODEL_SERVING_AGENT_TS = `/**
 * <APP_NAME> — apx-agent on Databricks Model Serving.
 */
import { createAgentPlugin } from 'appkit-agent';

export const agent = createAgentPlugin({
  name: '<APP_NAME>',
  model: 'databricks-claude-sonnet-4-6',
  instructions: 'You are a helpful assistant.',
  tools: [],
});
`;

const MODEL_SERVING_APP_TS = `/**
 * <APP_NAME> — Express app exposing the /invocations route.
 */
import express from 'express';
import { compileToChatAgent, mountInvocationsRoute } from 'appkit-agent';
import { agent } from './agent.js';

const app = express();
app.use(express.json());

const compiled = compileToChatAgent({ agent: agent.exports(), model: 'databricks-claude-sonnet-4-6' });
mountInvocationsRoute({ app, chatAgent: compiled as any });

const port = Number(process.env.PORT ?? 8000);
app.listen(port, () => {
  // eslint-disable-next-line no-console
  console.log('listening on', port);
});
`;

const MODEL_SERVING_PACKAGE_JSON = `{
  "name": "<APP_NAME>",
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "build": "tsc",
    "start": "node dist/app.js"
  },
  "dependencies": {
    "appkit-agent": "file:..",
    "express": "^5.0.0"
  },
  "devDependencies": {
    "@types/express": "^5.0.0",
    "typescript": "^5.0.0"
  }
}
`;

const MODEL_SERVING_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "Bundler",
    "outDir": "dist",
    "rootDir": ".",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["agent.ts", "app.ts"]
}
`;

const MODEL_SERVING_README = `# <APP_NAME>

apx-agent project targeting Databricks Model Serving.

\`\`\`bash
npm install
npm run build
node dist/app.js   # serves on http://localhost:8000
\`\`\`
`;

// ---------------------------------------------------------------------------
// Template — apps target (the main port)
// ---------------------------------------------------------------------------

const APPS_AGENT_TS = `/**
 * <APP_NAME> — apx-agent on Databricks Apps via mountResponsesAgent.
 *
 * Generated by \`apx scaffold <APP_NAME> --target apps\`. Edit this file to
 * define your agent.
 */
import { createAgentPlugin } from 'appkit-agent';

export const agent = createAgentPlugin({
  name: '<APP_NAME>',
  model: 'databricks-claude-sonnet-4-6',
  instructions: 'You are a helpful assistant.',
  tools: [
    // ucFunctionTool({...}),
    // genieTool({...}),
  ],
});
`;

const APPS_INDEX_TS = `/**
 * <APP_NAME> agent server entry — compiles the agent and exports the
 * ResponsesAgent invoke / stream pair.
 */
import { compileToResponsesAgent } from 'appkit-agent';
import { agent } from './agent.js';

export const LLM_ENDPOINT = process.env.APX_MODEL ?? 'databricks-claude-sonnet-4-6';

export const responsesAgent = compileToResponsesAgent({
  agent: agent.exports(),
  model: LLM_ENDPOINT,
});
`;

const APPS_START_TS = `/**
 * <APP_NAME> — start the agent HTTP server.
 *
 * Mounts \`POST /invocations\` (and \`/api/invocations\`) using
 * \`mountResponsesAgent\`. The Apps proxy injects
 * \`X-Forwarded-Access-Token\`, which the compiled responses agent reads
 * directly via \`extractOboHeaders\` — no caller bridge needed.
 */
import express from 'express';
import { mountResponsesAgent } from 'appkit-agent';
import { responsesAgent } from './index.js';

const app = express();
app.use(express.json({ limit: '10mb' }));

app.get('/health', (_req, res) => {
  res.json({ ok: true });
});

mountResponsesAgent({ app, agent: responsesAgent });

const port = Number(process.env.DATABRICKS_APP_PORT ?? process.env.PORT ?? 8000);
app.listen(port, () => {
  // eslint-disable-next-line no-console
  console.log('<APP_NAME> agent server listening on', port);
});
`;

const APPS_PACKAGE_JSON = `{
  "name": "<APP_NAME>",
  "version": "0.1.0",
  "type": "module",
  "main": "dist/agent_server/start.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/agent_server/start.js",
    "dev": "tsx agent_server/start.ts"
  },
  "dependencies": {
    "appkit-agent": "file:..",
    "express": "^5.0.0"
  },
  "devDependencies": {
    "@types/express": "^5.0.0",
    "tsx": "^4.20.0",
    "typescript": "^5.0.0"
  }
}
`;

const APPS_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "Bundler",
    "outDir": "dist",
    "rootDir": ".",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": false
  },
  "include": ["agent_server/**/*.ts"]
}
`;

const APPS_DATABRICKS_YML = `bundle:
  name: <APP_NAME>

# Apps deploys the .build/ tree as the source-code-path. Override the
# .gitignore that excludes it so DAB sync can upload the built JS.
sync:
  include:
    - .build/**

variables:
  workspace_user:
    description: User who owns the experiment
    default: \${workspace.current_user.userName}
  llm_endpoint_name:
    description: Foundation model endpoint the agent calls.
    default: databricks-claude-sonnet-4-6

# Build script — invoked by \`databricks bundle deploy\` (and explicitly by
# \`apx deploy --target apps\` before validate).
artifacts:
  default:
    build: |
      mkdir -p .build
      npm install
      npm run build
      cp package.json .build/
      cp -r dist .build/
      cp -r node_modules .build/ 2>/dev/null || true
      # appkit-agent is a "file:.." dep, so node_modules/appkit-agent is a
      # symlink to the local framework build. The deployed container can't
      # resolve "..", and npm doesn't hoist the framework's own deps (zod,
      # commander, ...) into this project. Materialize the framework's dist +
      # package.json in place of the symlink, then production-install its
      # (published) runtime deps so the bundle is self-contained.
      rm -rf .build/node_modules/appkit-agent
      mkdir -p .build/node_modules/appkit-agent
      cp -rL node_modules/appkit-agent/dist node_modules/appkit-agent/package.json .build/node_modules/appkit-agent/
      (cd .build/node_modules/appkit-agent && npm install --omit=dev --no-package-lock --no-audit --no-fund)

resources:
  apps:
    <APP_NAME>:
      name: <APP_NAME>
      description: <APP_NAME> apx-agent
      source_code_path: ./.build
      resources:
        - name: llm-endpoint
          description: Foundation model endpoint used by the agent.
          serving_endpoint:
            name: \${var.llm_endpoint_name}
            permission: CAN_QUERY

      config:
        command:
          - node
          - dist/agent_server/start.js
        env:
          - name: APX_MODEL
            value: \${var.llm_endpoint_name}

targets:
  dev:
    mode: development
    default: true
  prod:
    mode: production
    resources:
      apps:
        <APP_NAME>:
          name: <APP_NAME>
`;

const APPS_ENV_EXAMPLE = `DATABRICKS_CONFIG_PROFILE=
DATABRICKS_HOST=
APX_MODEL=databricks-claude-sonnet-4-6
`;

const APPS_GITIGNORE = `node_modules/
dist/
.build/
.env
.env.local
*.log
`;

const APPS_README = `# <APP_NAME>

apx-agent project targeting Databricks Apps (TypeScript).

## Setup

\`\`\`bash
npm install
\`\`\`

## Local dev

\`\`\`bash
npm run dev
# in another shell:
curl -X POST http://localhost:8000/invocations \\
  -H 'Content-Type: application/json' \\
  -d '{"input":[{"role":"user","content":"hi"}]}'
\`\`\`

## Deploy

\`\`\`bash
apx deploy --target apps
\`\`\`

Validates the bundle, deploys, runs the app, then polls until the workspace
reports the app is RUNNING.

## Edit

Define your agent + tools in \`agent_server/agent.ts\`.
`;

// ---------------------------------------------------------------------------
// File-writing helpers
// ---------------------------------------------------------------------------

function sub(template: string, name: string): string {
  return template.replaceAll('<APP_NAME>', name);
}

/** Deps overridable by tests — defaults to real fs. */
export interface ScaffoldDeps {
  writeFile?: (path: string, content: string) => void;
  mkdir?: (path: string) => void;
  exists?: (path: string) => boolean;
  /** Optional logger; defaults to console.log. */
  log?: (msg: string) => void;
  /** Optional list-children — defaults to readdirSync. */
  readdir?: (path: string) => string[];
}

function defaultDeps(): Required<ScaffoldDeps> {
  return {
    writeFile: (path, content) => {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, content);
    },
    mkdir: (path) => mkdirSync(path, { recursive: true }),
    exists: (path) => existsSync(path),
    log: (msg) => {
      // eslint-disable-next-line no-console
      console.log(msg);
    },
    readdir: (path) => readdirSync(path),
  };
}

function scaffoldModelServing(
  target: string,
  name: string,
  force: boolean,
  deps: Required<ScaffoldDeps>,
): void {
  const files: Record<string, string> = {
    'agent.ts': sub(MODEL_SERVING_AGENT_TS, name),
    'app.ts': sub(MODEL_SERVING_APP_TS, name),
    'package.json': sub(MODEL_SERVING_PACKAGE_JSON, name),
    'tsconfig.json': MODEL_SERVING_TSCONFIG,
    'README.md': sub(MODEL_SERVING_README, name),
  };
  writeAll(target, files, force, deps);
}

function scaffoldApps(
  target: string,
  name: string,
  force: boolean,
  deps: Required<ScaffoldDeps>,
): void {
  const files: Record<string, string> = {
    'package.json': sub(APPS_PACKAGE_JSON, name),
    'tsconfig.json': APPS_TSCONFIG,
    'databricks.yml': sub(APPS_DATABRICKS_YML, name),
    '.env.example': APPS_ENV_EXAMPLE,
    '.gitignore': APPS_GITIGNORE,
    'README.md': sub(APPS_README, name),
    'agent_server/agent.ts': sub(APPS_AGENT_TS, name),
    'agent_server/index.ts': sub(APPS_INDEX_TS, name),
    'agent_server/start.ts': sub(APPS_START_TS, name),
  };
  writeAll(target, files, force, deps);
}

function writeAll(
  target: string,
  files: Record<string, string>,
  force: boolean,
  deps: Required<ScaffoldDeps>,
): void {
  for (const [rel, content] of Object.entries(files)) {
    const path = join(target, rel);
    if (deps.exists(path) && !force) {
      deps.log(`  skip   ${path} (exists; pass --force to overwrite)`);
      continue;
    }
    deps.writeFile(path, content);
    deps.log(`  write  ${path}`);
  }
}

// ---------------------------------------------------------------------------
// Commander registration
// ---------------------------------------------------------------------------

// The project name is substituted into databricks.yml (bundle/resource name)
// and package.json ("name"), and used as a directory segment. Restrict it to a
// safe charset so the generated files stay valid and the path cannot escape the
// target dir. Must start alphanumeric; allows hyphen/underscore/dot internally;
// rejects path separators (M/L14 — robustness, not a security boundary).
const PROJECT_NAME_RE = /^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$/;

const ScaffoldOptionsSchema = z.object({
  name: z
    .string()
    .min(1, 'project name is required')
    .regex(
      PROJECT_NAME_RE,
      'project name must start and end with a letter or digit and contain only letters, digits, hyphens, underscores, or dots (no path separators)',
    ),
  dir: z.string().min(1).default('.'),
  target: z.enum(['model-serving', 'apps']).default('model-serving'),
  force: z.boolean().default(false),
});

export interface ScaffoldCommandDeps extends ScaffoldDeps {}

export function registerScaffoldCommand(
  program: Command,
  deps: ScaffoldCommandDeps = {},
): void {
  const resolved = { ...defaultDeps(), ...deps };

  program
    .command('scaffold <name>')
    .description('Generate a new agent project at <name>.')
    .option(
      '--dir <directory>',
      'Target directory. Default: current directory.',
      '.',
    )
    .option(
      '--target <target>',
      "Deployment target ('model-serving' or 'apps'). Default: model-serving.",
      'model-serving',
    )
    .option('--force', 'Overwrite existing files.', false)
    .action(
      async (
        name: string,
        rawOpts: { dir?: string; target?: string; force?: boolean },
      ) => {
        const opts = ScaffoldOptionsSchema.parse({
          name,
          dir: rawOpts.dir,
          target: rawOpts.target,
          force: Boolean(rawOpts.force),
        });
        const target = resolve(opts.dir, opts.name);

        if (resolved.exists(target) && !opts.force) {
          let children: string[] = [];
          try {
            children = resolved.readdir(target);
          } catch {
            children = [];
          }
          if (children.length > 0) {
            throw new Error(
              `${target} already exists and is not empty. Pass --force to overwrite.`,
            );
          }
        }
        resolved.mkdir(target);

        if (opts.target === 'apps') {
          scaffoldApps(target, opts.name, opts.force, resolved);
        } else {
          scaffoldModelServing(target, opts.name, opts.force, resolved);
        }
        resolved.log('');
        resolved.log(`Scaffolded ${opts.name} at ${target} (target=${opts.target}).`);
        if (opts.target === 'apps') {
          resolved.log(`Next: cd ${opts.name} && npm install && npm run dev`);
        } else {
          resolved.log(`Next: cd ${opts.name} && npm install && npm run build`);
        }
      },
    );
}
