"""hello-world — apx-agent root agent (ADK-style top-level definition).

Generated by ``apx scaffold hello-world --target apps``.

Edit this file to define your agent. ``agent`` is the canonical top-level
symbol that ``agent_server/start_server.py`` imports + wraps for the
Databricks Apps runtime. The same symbol is consumed by
``apx deploy --target model-serving`` if you also publish to a serving
endpoint.

The Apps runtime boilerplate — ``compile_to_responses_agent``,
``@invoke()`` / ``@stream()`` registration, MCP mounting — lives in
``agent_server/start_server.py`` so this file stays focused on the
agent's behavior.
"""
from __future__ import annotations

from apx_agent import Agent, tool


@tool
def echo(message: str) -> str:
    """Echo the user's message back.

    Replace this with your real tool(s) — pure-Python ``@tool`` callables,
    ``uc_function_tool(...)``, ``genie_tool(...)``, ``vector_search_tool(...)``,
    or remote sub-agent URLs in ``sub_agents=[...]``.
    """
    return f"echo: {message}"


# Define your agent. Add tools / sub-agents / memory stores here.
agent = Agent(
    name="hello-world",
    instructions="You are a helpful assistant.",
    tools=[echo],
)
