"""hello-world — apx-agent root agent (ADK-style top-level definition).

Generated by ``apx scaffold hello-world --target apps``.

Edit this file to define your agent. ``agent`` is the canonical top-level
symbol that ``agent_server/start_server.py`` imports + wraps for the
Databricks Apps runtime. The same symbol is consumed by
``apx deploy --target model-serving`` if you also publish to a serving
endpoint.

The Apps runtime boilerplate — ``compile_to_responses_agent``,
``@invoke()`` / ``@stream()`` registration, MCP mounting — lives in
``agent_server/start_server.py`` so this file stays focused on the
agent's behavior.
"""
from __future__ import annotations

from apx_agent import DataAgent


# A governed data agent over Databricks' built-in ``samples.nyctaxi`` dataset.
# It answers questions grounded in that schema and queries via a SQL tool that
# runs as the calling user — their Unity Catalog grants apply.
#
# Make it your own:
#   * point it at your own data:  DataAgent("main", "sales", name="hello-world")
#   * pass ``ws=WorkspaceClient()`` to auto-discover the schema's tables + UC
#     functions and ground the instructions in the real columns
#   * add ``genie_space=...`` / ``vector_index=...`` for Genie or Vector Search
#   * or drop back to a plain ``Agent(tools=[...])`` with your own ``@tool``s
agent = DataAgent("samples", "nyctaxi", name="hello-world")
