"""hello-world — apx-agent root agent (ADK-style top-level definition).

Generated by ``apx-agent scaffold hello-world --target apps``.

Edit this file to define your agent. ``agent`` is the canonical top-level
symbol that ``agent_server/start_server.py`` imports + wraps for the
Databricks Apps runtime. The same symbol is consumed by
``apx-agent deploy --target model-serving`` if you also publish to a serving
endpoint.

The Apps runtime boilerplate — ``compile_to_responses_agent``,
``@invoke()`` / ``@stream()`` registration, MCP mounting — lives in
``agent_server/start_server.py`` so this file stays focused on the
agent's behavior.
"""
from __future__ import annotations

from apx_agent import DataAgent


# A governed data agent over Databricks' built-in ``samples.nyctaxi`` dataset.
# It answers questions grounded in that schema and queries via a SQL tool that
# runs as the calling user — their Unity Catalog grants apply.
#
# Peer Apps wired via Topology / Discover (URLs in App env as APX_PEER_*).
agent = DataAgent(
    "samples",
    "nyctaxi",
    name="hello-world",
    # OKF grounding bundle (same idea as Google knowledge-catalog / BigQuery
    # enrichment agents): schema + semantics under .apx/okf, curated in Grounding.
    knowledge="./.apx/okf",
    sub_agents=[
        "$APX_PEER_MCP_DATA_INSPECTOR_URL",
        "$APX_PEER_MCP_DATA_TRIAGE_AGENT_URL",
    ],
)
