"""FastAPI entry point for Databricks Apps — AUTO-GENERATED by apx-agent scaffold.

Don't edit this file. Edit ``../agent.py`` (or the deeper backend module
it re-exports) to change the agent.

slack-agent is unique in that it ALSO mounts the Slack webhook surface
(``/slack/events``, ``/slack/install``, ``/slack/oauth/callback``) on
the same FastAPI app. Slack hits those endpoints directly; the router
validates Slack signatures, exchanges Slack user identity for the
calling user's Databricks token, then delegates to the agent over
``/invocations``.

Driven by the ``uvicorn`` command in ``databricks.yml`` at deploy time.
"""

from __future__ import annotations

import os

from mlflow.genai.agent_server import AgentServer, invoke, stream

from apx_agent import compile_to_responses_agent, mount_mcp_endpoints

from agent import agent
from webhook import router as _slack_router

MODEL = os.environ.get("APX_MODEL", "databricks-claude-sonnet-4-6")

_invoke_fn, _stream_fn = compile_to_responses_agent(agent, model=MODEL)


@invoke()
def non_streaming(request):
    """Non-streaming request handler — POST /invocations."""
    return _invoke_fn(request)


@stream()
def streaming(request):
    """Streaming request handler — POST /invocations with stream=true."""
    yield from _stream_fn(request)


server = AgentServer(agent_type="ResponsesAgent")
app = server.app

# Slack webhook surface — slack-agent specific. Mount BEFORE MCP so
# /slack/* takes precedence over any catch-all.
app.include_router(_slack_router)

mount_mcp_endpoints(app, agent)


if __name__ == "__main__":
    server.run("agent_server.start_server:app")
