"""Hand native rollout and hosting decisions to the Agent Bricks CLI."""

from __future__ import annotations

import json
import importlib.metadata
import subprocess
import sys
import shutil
from pathlib import Path
from typing import Any, TYPE_CHECKING

import click

if TYPE_CHECKING:
    from ._models import AgentConfig

MARKER = "# Generated by APX from agent declarations; do not edit."


def cleanup_app_runtime(ws: Any, app_name: str, *, native: bool = False) -> bool:
    """Clean the owned Runtime Store; return whether the App still needs deletion."""
    from databricks.sdk.errors import NotFound

    try:
        app = ws.apps.get(app_name)
    except NotFound:
        app = None
    except Exception as exc:
        raise click.ClickException("Cannot read the App for ownership checks; nothing deleted. Check workspace access and retry.") from exc
    # APX's managed deployments use the CLI's required prefix or a named
    # App Space. The declaration also covers older native project names.
    space = getattr(app, "space", None)
    if app is not None and not (native or app_name.startswith("agent-bricks-") or isinstance(space, str) and space):
        return True
    try:
        from databricks_agentbricks.lakebase_runtime_store import delete
        from databricks_agentbricks.errors import AgentCliError
        from databricks_agentkit._api_client import _AgentBricksApiClient
    except ImportError as exc:
        raise click.ClickException("Install apx-agent[agentbricks] for native cleanup; teardown stopped.") from exc
    try:
        client = _AgentBricksApiClient(workspace_client=ws)
        if app is None:
            try:
                client.get_runtime_store(app_name)
            except AgentCliError as exc:
                if exc.error_code == "NOT_FOUND":
                    return False
                raise
            raise click.ClickException("App identity is missing while its Runtime Store still exists; refusing unverified cleanup.")
        principal = app.service_principal_client_id
        if app.name != app_name or not isinstance(principal, str) or not principal:
            raise click.ClickException("Cannot verify the App service principal for Runtime Store ownership.")
        delete(client, app_name, principal)
    except Exception as exc:
        raise click.ClickException("Native Runtime Store cleanup failed; App deletion stopped. Check ownership and workspace access, then retry.") from exc
    return True


def compile_native_app(config: AgentConfig) -> dict[str, Any]:
    """Compile the native app command and environment without a Bundle."""
    from ._memory_wiring import declared_replica_bounds, declared_max_replicas, scaled_in_memory, scaled_in_memory_error

    if scaled_in_memory(config, ws=None):
        raise click.ClickException(scaled_in_memory_error(declared_max_replicas(config)))
    env = [
        {"name": "APX_MODEL", "value": config.model},
        {"name": "MLFLOW_TRACKING_URI", "value": "databricks"},
        {"name": "APX_AGENT_MLFLOW_AUTOLOG", "value": "1"},
    ]
    app: dict[str, Any] = {
        "name": config.name if config.name.startswith("agent-bricks-") else f"agent-bricks-{config.name}",
        "source_code_path": ".build",
        "config": {"command": ["python", "-m", "apx_agent._serve"], "env": env},
    }
    bounds = declared_replica_bounds(config)
    if bounds is not None:
        app.update(compute_min_instances=bounds.min, compute_max_instances=bounds.max)
        env.append({"name": "APX_DECLARED_INSTANCES", "value": str(bounds.max)})
    return app


def stage_native_source(cwd: Path, *, include: tuple[str, ...] = ()) -> None:
    """Stage generated project sources; rebuild only an APX-owned staging tree.

    ``include`` is an explicit list of extra project-relative paths copied after
    the standard files. It is empty unless the Apps API declaration sets it.
    """
    source = cwd / ".build"
    ownership = source / ".apx-native-build"
    inputs = [cwd / name for name in (
        "agent.py", "tools.py", "sub_agents", "agent_server", "scripts", "README.md",
        ".apx-agent", ".apx", "skills",
    )]
    inputs.extend(cwd.glob("apx_agent-*.whl"))
    extra = [_included_path(cwd, rel) for rel in include]
    for path in [source, cwd / "pyproject.toml", cwd / "uv.lock", *inputs, *extra]:
        if path.is_symlink() or (path.is_dir() and any(child.is_symlink() for child in path.rglob("*"))):
            raise click.ClickException("Refusing symlinked native deployment source: " + str(path))
    if source.exists():
        if not ownership.is_file() or ownership.read_text() != MARKER:
            raise click.ClickException("Refusing to replace an unowned .build directory; preserve it before rebuilding the native project.")
        shutil.rmtree(source)
    source.mkdir()
    ownership.write_text(MARKER)
    for path in inputs:
        if path.is_dir():
            shutil.copytree(path, source / path.name, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".venv"))
        elif path.is_file():
            shutil.copy2(path, source / path.name)
    for path in extra:
        _copy_included(cwd, path, source)


def _included_path(cwd: Path, rel: str) -> Path:
    """Resolve one declared include path and refuse escapes or missing files."""
    if not rel or rel.startswith(("/", "\\")) or ".." in Path(rel).parts:
        raise click.ClickException(f"deploy.include path must stay inside the project: {rel!r}")
    path = (cwd / rel).resolve()
    if not path.is_relative_to(cwd.resolve()):
        raise click.ClickException(f"deploy.include path must stay inside the project: {rel!r}")
    if not path.exists():
        raise click.ClickException(f"deploy.include path does not exist: {rel}")
    return path


def _copy_included(cwd: Path, path: Path, source: Path) -> None:
    dest = source / path.relative_to(cwd.resolve())
    dest.parent.mkdir(parents=True, exist_ok=True)
    if path.is_dir():
        shutil.copytree(path, dest, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".venv"))
    else:
        shutil.copy2(path, dest)


def validate_cli_deployment(
    doc: dict[str, Any], *, bundle_key: str, app_name: str, profile: str | None,
    no_run: bool,
) -> None:
    """Refuse configuration the CLI cannot carry before any provisioning."""
    resources = doc.get("resources", {})
    if doc.get("include") or doc.get("permissions"):
        raise click.ClickException("Agent Bricks deployment requires a self-contained configuration without bundle permissions.")
    if set(resources) != {"apps"} or set(resources["apps"]) != {bundle_key}:
        raise click.ClickException("Agent Bricks cannot deploy additional bundle resources; regenerate the native project.")
    validate_native_app(resources["apps"][bundle_key], app_name=app_name, profile=profile, no_run=no_run)
    for target in doc.get("targets", {}).values():
        if target.get("permissions") or target.get("presets"):
            raise click.ClickException("Agent Bricks cannot carry target permissions or presets.")
        override = target.get("resources", {})
        if set(override) - {"apps"} or set(override.get("apps", {})) - {bundle_key}:
            raise click.ClickException("Agent Bricks cannot deploy additional target resources.")
        if set(override.get("apps", {}).get(bundle_key, {})) - {"name"}:
            raise click.ClickException("Put native app configuration in the root declaration; target overrides support only name.")


def validate_native_app(app: dict[str, Any], *, app_name: str, profile: str | None, no_run: bool) -> None:
    """Validate native deployment options before building or provisioning."""
    try:
        distribution = importlib.metadata.distribution("databricks-agentbricks")
    except importlib.metadata.PackageNotFoundError as exc:
        raise click.ClickException("Install apx-agent[agentbricks] to deploy the durable target.") from exc
    # Importing the CLI patches Click's UsageError globally. Keep it in the
    # subprocess; inspect installation metadata without executing the entrypoint.
    if not any(entry.group == "console_scripts" and entry.name == "agentbricks"
               for entry in distribution.entry_points):
        raise click.ClickException("The installed Agent Bricks CLI has an unsupported deploy contract.")
    if not profile:
        raise click.ClickException("Agent Bricks deployment requires an explicit --profile.")
    if no_run:
        raise click.ClickException("Agent Bricks deploy includes rollout; --no-run is unsupported.")
    if not app_name.startswith("agent-bricks-") or len(app_name) > 30:
        raise click.ClickException(
            "Agent Bricks requires an app name starting with agent-bricks- and at most 30 characters. "
            "Regenerate the project or explicitly choose a prefixed --app-name; existing Apps are not renamed."
        )
    unsupported = set(app) - {
        "name", "source_code_path", "config", "user_api_scopes",
        "compute_min_instances", "compute_max_instances",
    }
    if unsupported:
        raise click.ClickException("Agent Bricks cannot represent app fields: " + ", ".join(sorted(unsupported)))
    minimum = app.get("compute_min_instances")
    maximum = app.get("compute_max_instances")
    if (minimum is not None or maximum is not None) and (
        type(minimum) is not int or minimum != maximum or not 1 <= minimum <= 5
    ):
        raise click.ClickException("Agent Bricks requires a fixed instance count between 1 and 5.")
    config = app.get("config", {})
    if set(config) - {"command", "env"}:
        raise click.ClickException("Agent Bricks supports only command and env in the compiled app configuration.")
    for entry in config.get("env", []):
        name = entry.get("name", "")
        if name.startswith("DATABRICKS_AGENTBRICKS_RUNTIME_STORE_") or name in {
            "AGENT_MEMORY_STORE", "AGENT_SESSION_STORE", "MLFLOW_EXPERIMENT_ID",
            "PIP_INDEX_URL", "UV_INDEX_URL", "UV_DEFAULT_INDEX",
        }:
            raise click.ClickException(f"{name} is owned by Agent Bricks; use the declared store/tracing binding.")
        if name == "MLFLOW_TRACKING_URI" and entry.get("value") != "databricks":
            raise click.ClickException("Agent Bricks deployment requires workspace MLflow tracing.")
        if "value_from" in entry or "valueFrom" in entry:
            raise click.ClickException("Agent Bricks cannot carry bundle resource-backed environment references.")


def deploy_native_project(
    source: Path, *, app: dict[str, Any], app_name: str, profile: str,
    experiment_name: str | None,
    transient_env_keys: list[str],
) -> dict[str, Any]:
    """Stage resolved runtime config, invoke the CLI, and verify its result."""
    import yaml
    from databricks_agentbricks.agent_project import AgentProject

    manifest = source / "agent.toml"
    app_yaml = source / "app.yaml"
    if source.is_symlink() or manifest.is_symlink() or app_yaml.is_symlink():
        raise click.ClickException("Refusing a symlinked Agent Bricks deployment artifact.")
    if app_yaml.exists() and not app_yaml.read_text().startswith(MARKER):
        raise click.ClickException("Refusing to overwrite authored app.yaml in the staged source.")
    project = AgentProject.load(source)
    project.set_deployment_name(app_name)
    if experiment_name is not None:
        project.bind_tracing(experiment_name)
    project.write()
    runtime = app.get("config", {})
    if not runtime.get("command"):
        raise click.ClickException("Native deployment requires a compiled app command.")
    encoded = yaml.safe_dump(runtime, sort_keys=False)
    if "${" in encoded:
        raise click.ClickException("Native deployment contains unresolved configuration references.")
    app_yaml.write_text(MARKER + "\n" + encoded)
    command = [sys.executable, "-m", "databricks_agentbricks.cli.app",
               "--profile", profile, "--output", "json", "deploy", app_name,
               "--source", str(source)]
    if project.user_auth.required:
        command.append("--allow-user-scope-update")
    if app.get("compute_min_instances") is not None:
        command.extend(["--instances", str(app["compute_min_instances"])])
    try:
        process = subprocess.run(command, capture_output=True, text=True, check=False, cwd=source)
    finally:
        if app_yaml.is_symlink():
            raise click.ClickException("Refusing to scrub a symlinked deployment manifest.")
        saved = yaml.safe_load(app_yaml.read_text())
        saved["env"] = [entry for entry in saved.get("env", []) if entry.get("name") not in transient_env_keys]
        # The CLI rewrites YAML without comments. Restore ownership for redeploys.
        app_yaml.write_text(MARKER + "\n" + yaml.safe_dump(saved, sort_keys=False))
    if process.returncode:
        # The CLI can echo environment values and backend details. Keep its raw
        # output out of APX errors and deployment manifests.
        raise click.ClickException(f"Agent Bricks deploy failed (exit {process.returncode}); deployment is unverified.")
    # The CLI emits progress text before its final JSON object, even in JSON mode.
    result = None
    for index, char in enumerate(process.stdout):
        if char != "{":
            continue
        try:
            candidate, end = json.JSONDecoder().raw_decode(process.stdout[index:])
        except ValueError:
            continue
        if not process.stdout[index + end:].strip() and isinstance(candidate, dict):
            result = candidate
            break
    if result is None or result.get("deployment") != app_name:
        raise click.ClickException("Agent Bricks did not confirm the requested deployment identity; rollout is unverified.")
    if any(result.get(key) for key in ("store_grant_error", "trace_grant_error", "trace_setup_error")):
        raise click.ClickException("Agent Bricks reported incomplete store/tracing setup; the App may be live but deployment is unverified.")
    if (project.memory_store or project.session_store) and result.get("store_grant") != "granted":
        raise click.ClickException("Agent Bricks did not confirm the declared store grants.")
    if experiment_name and (not result.get("trace_experiment_id") or result.get("trace_grant") != "granted"):
        raise click.ClickException("Agent Bricks did not confirm the declared tracing binding and grant.")
    return result
