"""FastAPI routes for the /_apx/builder visual builder SPA.

Serves the pre-built Vite SPA assets out of the wheel, plus:
  * a SPA-fallback route so client-side routing works
  * a POST /save endpoint the canvas hits to write generated agent.py code
    plus a .apx-builder.json sidecar capturing the canvas layout so the user
    can reopen the same graph later.
"""
from __future__ import annotations

import importlib.resources as ir
import json
import os
import tempfile
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field


def _dist_root() -> Path:
    """Locate the bundled _builder_ui_dist/ directory inside the installed package.

    Returns a real filesystem path via importlib.resources.files(), which works
    for both regular installs and zip-imported wheels (since Python 3.9).
    """
    return Path(str(ir.files("apx_agent").joinpath("_builder_ui_dist")))


def _resolve_workspace_client(request: Request):
    """Resolve the OBO WorkspaceClient from request state, falling back to env-based default.

    On Databricks Apps the per-request OBO client is stashed on request.state by
    setup_agent.  For local development (apx dev / uvicorn --reload) it falls
    back to env-based credentials (DATABRICKS_TOKEN etc.).
    """
    ws = getattr(request.state, "workspace_client", None)
    if ws is not None:
        return ws
    from databricks.sdk import WorkspaceClient
    return WorkspaceClient()


SENTINEL = "# Generated by apx-agent visual builder"


class SavePayload(BaseModel):
    code: str = Field(..., description="The rendered Python source to write.")
    graph: dict[str, Any] = Field(
        default_factory=dict,
        description="The canvas graph state (nodes/edges/config); written to .apx-builder.json sidecar.",
    )
    target: str | None = Field(
        default=None,
        description="Optional relative path for the generated file. Defaults to 'agent.py'. Must be a path under cwd; absolute paths and ../ escapes are rejected.",
    )


def _resolve_target(target: str | None) -> Path:
    """Resolve the canvas's `target` field to an absolute path under cwd.

    Rejects absolute paths and any path that resolves outside the cwd tree
    (defense against path-traversal). Returns the absolute Path.
    """
    rel = Path(target) if target else Path("agent.py")
    if rel.is_absolute():
        raise HTTPException(status_code=400, detail="absolute paths are not allowed")
    cwd = Path.cwd().resolve()
    resolved = (cwd / rel).resolve()
    try:
        resolved.relative_to(cwd)
    except ValueError:
        raise HTTPException(status_code=400, detail="target must be under the current working directory")
    return resolved


def _atomic_write(path: Path, content: str) -> None:
    """Write `content` to `path` atomically (tmp + rename, same directory)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        suffix=".tmp", prefix=path.name + ".", dir=str(path.parent)
    )
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except Exception:
        Path(tmp).unlink(missing_ok=True)
        raise


def build_builder_router() -> APIRouter:
    """Router that mounts the visual builder SPA at /_apx/builder/* + save endpoint."""
    router = APIRouter()

    @router.get("/_apx/builder", include_in_schema=False)
    @router.get("/_apx/builder/", include_in_schema=False)
    async def builder_index():
        index = _dist_root() / "index.html"
        if not index.exists():
            raise HTTPException(
                status_code=503,
                detail=(
                    "Visual builder assets are not bundled in this install. "
                    "Build them via `cd python/builder-ui && npm run build:dist` "
                    "before installing the wheel."
                ),
            )
        return FileResponse(index, media_type="text/html")

    @router.post("/_apx/builder/save", include_in_schema=False)
    async def builder_save(payload: SavePayload, force: int = 0):
        target = _resolve_target(payload.target)
        # Refuse-to-clobber: if target exists, contents must include SENTINEL
        # OR caller must pass ?force=1.
        if target.exists() and not force:
            existing = target.read_text(errors="ignore")
            if SENTINEL not in existing:
                raise HTTPException(
                    status_code=409,
                    detail=(
                        f"{target} exists and doesn't look canvas-generated "
                        f"(missing '{SENTINEL}' sentinel). Pass ?force=1 to overwrite."
                    ),
                )
        sidecar = target.with_name(".apx-builder.json")
        _atomic_write(target, payload.code)
        _atomic_write(sidecar, json.dumps(payload.graph, indent=2))
        return {
            "status": "ok",
            "agent_py": str(target),
            "sidecar": str(sidecar),
        }

    @router.get("/_apx/builder/uc-functions", include_in_schema=False)
    async def list_uc_functions(request: Request, catalog: str, schema: str):
        ws = _resolve_workspace_client(request)
        try:
            funcs = list(ws.functions.list(catalog_name=catalog, schema_name=schema))
        except Exception as e:
            raise HTTPException(status_code=502, detail=str(e))
        return {
            "functions": [
                {
                    "full_name": (
                        getattr(f, "full_name", None)
                        or f"{catalog}.{schema}.{getattr(f, 'name', '')}"
                    ),
                    "name": getattr(f, "name", ""),
                    "comment": getattr(f, "comment", "") or "",
                }
                for f in funcs
            ]
        }

    @router.get("/_apx/builder/vector-indexes", include_in_schema=False)
    async def list_vector_indexes(request: Request):
        ws = _resolve_workspace_client(request)
        try:
            endpoints = list(ws.vector_search_endpoints.list_endpoints())
            all_indexes = []
            for ep in endpoints:
                resp = ws.vector_search_indexes.list_indexes(endpoint_name=ep.name)
                for idx in resp.vector_indexes or []:
                    all_indexes.append(
                        {
                            "name": getattr(idx, "name", ""),
                            "endpoint_name": ep.name,
                            "index_type": getattr(idx, "index_type", ""),
                        }
                    )
        except Exception as e:
            raise HTTPException(status_code=502, detail=str(e))
        return {"indexes": all_indexes}

    @router.get("/_apx/builder/genie-spaces", include_in_schema=False)
    async def list_genie_spaces(request: Request):
        ws = _resolve_workspace_client(request)
        try:
            resp = ws.genie.list_spaces()
            spaces = [
                {
                    "space_id": getattr(s, "space_id", ""),
                    "title": getattr(s, "title", "") or "",
                    "description": getattr(s, "description", "") or "",
                }
                for s in (resp.spaces or [])
            ]
        except Exception as e:
            raise HTTPException(status_code=502, detail=str(e))
        return {"spaces": spaces}

    @router.get("/_apx/builder/{path:path}", include_in_schema=False)
    async def builder_asset(path: str):
        # Asset lookup first; fall back to index.html for SPA deep-link routes.
        target = _dist_root() / path
        if target.is_file():
            return FileResponse(target)
        index = _dist_root() / "index.html"
        if not index.exists():
            raise HTTPException(status_code=404, detail="builder not bundled")
        return FileResponse(index, media_type="text/html")

    return router
