"""Native DurableAgentServer target, sharing graph execution with other hosts."""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
from dataclasses import dataclass, replace
from typing import TYPE_CHECKING, Any, Callable, Awaitable

from ._agents import BaseAgent, LlmAgent
from ._compile import compile_to_langgraph
from ._graph_turn import run_graph_turn

if TYPE_CHECKING:
    from ._apps_authorization import AuthorizationPlan
    from ._models import AgentConfig


def build_native_manifest(*, config: AgentConfig, authorization_plan: AuthorizationPlan) -> str:
    """Compile the existing authorization plan into AgentKit's native contract."""
    from databricks_agentkit.runtime.tool_manifest import parse_user_auth
    from ._project_gen import _write_toml_section

    required = any(op.requires_request_context for op in authorization_plan.operations)
    required = required or bool(authorization_plan.app_dependencies) or config.memory is not None
    scopes = list(authorization_plan.user_api_scopes) if required else []
    auth = {"required": required, "additional_api_scopes": scopes}
    parse_user_auth({"auth": {"user": auth}})
    if config.recovery and required:
        raise ValueError("Request-user recovery is unsupported")
    lines = ["# Generated by APX from agent declarations; do not edit.", "schema_version = 1", ""]
    _write_toml_section(lines, "agent", {"framework": "langgraph", "server": "agentbricks"})
    _write_toml_section(lines, "auth.user", auth)
    if config.memory is not None and config.memory.type == "managed":
        _write_toml_section(lines, "memory_store", {"name": config.memory.store_name})
    if config.session is not None and config.session.type == "managed":
        _write_toml_section(lines, "session_store", {"name": config.session.store_name})
    return "\n".join(lines)


@dataclass(frozen=True)
class DurableHandlers:
    invoke: Callable[[Any, Any], Awaitable[dict[str, Any]]]


def _pending(graph: Any, config: dict[str, Any] | None) -> Any | None:
    if config is None:
        return None
    interrupts = graph.get_state(config).interrupts
    return interrupts[0].value if interrupts else None


def compile_durable_handlers(
    agent: BaseAgent,
    *,
    model: str,
    service_ws: Any,
    checkpointer: Any | None = None,
    require_user: bool = False,
    recovery: bool = False,
) -> DurableHandlers:
    """Build native message handlers; no MLflow request/response dependency.

    The SDK owns transient request-user credentials and session namespacing.
    The service client never fills a user slot.
    Recovery is opt-in and resumes invocation-tagged managed checkpoints.
    """
    if service_ws is None:
        raise ValueError("durable_agent_server requires an explicit service_ws runtime binding")
    from ._runtime_targets import RuntimeRequirements, inspect_target

    report = inspect_target(agent, target="durable_agent_server", checkpointer=checkpointer,
                            requirements=RuntimeRequirements(recovery=recovery, user_identity=require_user))
    report.require_compatible()
    require_user = require_user or report.user_identity_required
    if checkpointer is not None and not isinstance(agent, LlmAgent):
        raise ValueError("Checkpoint sessions currently require LlmAgent")

    def execute(value: Any, context: Any, emit_message: Callable[[Any], None] | None) -> dict[str, Any]:
        recovering = bool(getattr(context, "is_recovery", False))
        if recovering and not recovery:
            raise ValueError("recovery is not wired for durable_agent_server")
        if recovery and (not isinstance(getattr(context, "invocation_id", None), str) or not context.invocation_id):
            raise ValueError("recovery requires a non-empty invocation_id")
        from databricks_agentkit.runtime.auth import RequestAuthContext
        from databricks_agentkit.runtime.store import RUNTIME_STORE_LOCAL_ENV
        from ._defaults import DatabricksAppsHeaders

        auth = getattr(context, "request_auth", None)
        if recovery and auth is not None:
            raise ValueError("Request-user recovery is unsupported")
        if (require_user and auth is None) or (auth is not None and not isinstance(auth, RequestAuthContext)):
            raise ValueError("user_identity requires the SDK's active RequestAuthContext")
        user_ws = auth.client_for("user") if auth is not None else None
        headers = None
        if user_ws is not None:
            principal = user_ws.current_user.me().id
            if not isinstance(principal, str) or not principal:
                raise ValueError("user_identity could not resolve the authenticated principal")
            # Mirrors RequestAuthContext.from_headers' local test so local dev
            # never forwards the developer's profile credentials to a peer.
            local = (os.environ.get(RUNTIME_STORE_LOCAL_ENV) == "true"
                     or not os.environ.get("DATABRICKS_APP_NAME"))
            headers = DatabricksAppsHeaders(
                host=None, user_name=None, user_id=principal, user_email=None, request_id=None, token=None,
                auth_headers=None if local else (lambda: auth.client_for("user").config.authenticate()),
            )
        if isinstance(value, list):
            value = {"messages": value}
        if not isinstance(value, dict) or set(value) - {"messages", "resume"}:
            raise ValueError("Native input must contain messages and optional resume; session_id belongs in the top-level invocation envelope")
        messages = value.get("messages", [])
        if not isinstance(messages, list):
            raise ValueError("messages must be a list")
        # Durable invocation input is fresh chat input. Tool results and state
        # are produced by execution/checkpoints, never supplied by a caller.
        for message in messages:
            if not isinstance(message, dict) or set(message) - {"role", "content"}:
                raise ValueError("Each message must contain only role and content")
            if message.get("role") != "user" or not isinstance(message.get("content"), str):
                raise ValueError("Native input accepts user text messages only")
        resume = value.get("resume")
        if resume is not None and checkpointer is None:
            raise ValueError("Approval resume requires a checkpointed session")
        config = None
        if checkpointer is not None:
            session = context.session_id
            if not isinstance(session, str) or not session:
                raise ValueError("A checkpointed invocation requires a non-empty session_id")
            scope = [getattr(agent, "_name", None), session]
            if headers is not None:
                scope.insert(1, headers.user_id)
            key = hashlib.sha256(json.dumps(scope).encode()).hexdigest()
            config = {"configurable": {"thread_id": key, "actor_id": key}}
        from langchain_core.messages import HumanMessage

        graph = compile_to_langgraph(
            agent, ws=user_ws, service_ws=service_ws, model=model, headers=headers,
            **({"checkpointer": checkpointer} if checkpointer is not None else {}),
        )
        turn = run_graph_turn(
            graph, agent, [HumanMessage(content=m["content"]) for m in messages],
            config=config, resume=resume, read_interrupt=_pending,
            emit_message=emit_message,
            invocation_id=context.invocation_id if recovery else None,
            recovery=recovering,
        )
        if turn.approval_required is not None:
            return {"status": "interrupted", "messages": [], "approval_required": turn.approval_required}
        return {"status": "completed", "messages": [m.model_dump(mode="json") for m in turn.messages]}

    async def invoke(value: Any, context: Any) -> dict[str, Any]:
        loop = asyncio.get_running_loop()

        def emit_message(message: Any) -> None:
            # Native SDK persists and orders these events for SSE replay. Wait
            # for each write: a slow store must exert backpressure on generation.
            event = {"type": "agent.message.delta", "message": message.model_dump(mode="json")}
            asyncio.run_coroutine_threadsafe(context.emit(event), loop).result()

        # Sync graph/checkpoint tools run outside the server's event loop.
        can_emit = callable(getattr(context, "emit", None))
        result = await asyncio.to_thread(
            execute, value, context,
            emit_message if can_emit and not report.streaming_buffered else None,
        )
        if can_emit and report.streaming_buffered and result["status"] == "completed" and result["messages"]:
            # Only publish the final validated answer, never buffered intermediate
            # model/tool messages that the output checks did not approve.
            await context.emit({"type": "agent.message.completed", "message": result["messages"][-1]})
        return result

    return DurableHandlers(invoke=invoke)


def compile_to_durable_agent_server(
    agent: BaseAgent,
    *,
    model: str,
    service_ws: Any,
    checkpointer: Any | None = None,
    session_store: str | None = None,
    require_user: bool = False,
    recovery: bool = False,
) -> Any:
    """Create the optional SDK server without importing ResponsesAgent."""
    from ._runtime_targets import RuntimeRequirements, inspect_target

    inspect_target(agent, target="durable_agent_server", checkpointer=checkpointer,
                   session_store=session_store,
                   requirements=RuntimeRequirements(recovery=recovery, user_identity=require_user)).require_compatible()
    try:
        from databricks_agentkit.runtime.app import DurableAgentServer
    except ImportError as exc:
        raise ImportError("durable_agent_server requires the optional SDK; install apx-agent[agentbricks] in the host project") from exc
    if session_store is not None:
        if service_ws is None:
            raise ValueError("session_store requires an explicit service_ws runtime binding")
        from databricks_agentkit.langgraph.session_store import DatabricksSessionStoreSaver

        checkpointer = DatabricksSessionStoreSaver(session_store, workspace_client=service_ws)
    from databricks_agentkit.runtime.auth import InvocationAuthPolicy

    report = inspect_target(agent, target="durable_agent_server", checkpointer=checkpointer)
    policy = InvocationAuthPolicy.from_manifest(allow_missing=True)
    if require_user or report.user_identity_required:
        policy = replace(policy, user_required=True)
    if recovery and policy.requires_user:
        raise ValueError("recovery is incompatible with the manifest's request-user authentication")
    handlers = compile_durable_handlers(agent, model=model, service_ws=service_ws,
                                        checkpointer=checkpointer, require_user=policy.requires_user, recovery=recovery)
    app = DurableAgentServer(auth_policy=policy)
    app.invoke(handlers.invoke)
    if recovery:
        app.recover(handlers.invoke)

    from ._resources import _iter_sub_agents

    if list(_iter_sub_agents(agent)):
        from ._wiring import _chain_lifespan

        async def _materialize_sub_agents() -> None:
            # Card fetch registers each sub_agents URL as a callable delegate
            # (#436); the per-invocation graph compile picks the delegates up.
            await agent.fetch_remote_tools()

        _chain_lifespan(app, _materialize_sub_agents)

    @app.get("/readyz")
    async def readyz() -> Any:
        import uuid
        from fastapi.responses import JSONResponse

        try:
            await app._runtime.runtime_store.get(invocation_id=str(uuid.uuid4()))
        except Exception:
            return JSONResponse(status_code=503, content={
                "status": "degraded", "checks": {"runtime_store": "unreachable"},
            })
        return {"status": "ready", "checks": {
            "runtime_store": "ok", "durable": app._runtime.is_durable,
            "agent_execution": "not_probed",
        }}

    return app
