"""Tests for the /_apx/builder SPA static-asset routes."""
from __future__ import annotations

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from apx_agent._builder_routes import build_builder_router


@pytest.fixture
def app(tmp_path, monkeypatch):
    # Stage a minimal _builder_ui_dist with one HTML and one JS asset
    dist_root = tmp_path / "_builder_ui_dist"
    (dist_root / "assets").mkdir(parents=True)
    (dist_root / "index.html").write_text(
        "<!doctype html><html><body><div id='root'></div>"
        "<script src='/_apx/builder/assets/main.js'></script>"
        "</body></html>"
    )
    (dist_root / "assets" / "main.js").write_text("console.log('builder');")

    # Patch the dist-locator to point at our tmp tree
    monkeypatch.setattr(
        "apx_agent._builder_routes._dist_root",
        lambda: dist_root,
    )
    app = FastAPI()
    app.include_router(build_builder_router())
    return app


def test_index_served(app):
    client = TestClient(app)
    r = client.get("/_apx/builder/")
    assert r.status_code == 200
    assert "text/html" in r.headers["content-type"]
    assert "id='root'" in r.text


def test_asset_served(app):
    client = TestClient(app)
    r = client.get("/_apx/builder/assets/main.js")
    assert r.status_code == 200
    assert "javascript" in r.headers["content-type"]
    assert "console.log" in r.text


def test_spa_fallback(app):
    """Deep links like /_apx/builder/some/canvas-route fall back to index.html."""
    client = TestClient(app)
    r = client.get("/_apx/builder/some/canvas-route")
    assert r.status_code == 200
    assert "text/html" in r.headers["content-type"]
    assert "id='root'" in r.text


def test_save_writes_agent_py_and_sidecar(tmp_path, monkeypatch, app):
    """POST /save writes agent.py + .apx-builder.json in the cwd."""
    monkeypatch.chdir(tmp_path)
    client = TestClient(app)
    payload = {
        "code": (
            "# Generated by apx-agent visual builder\n"
            "from apx_agent import Agent\n"
            "agent = Agent(instructions='hi', tools=[])\n"
        ),
        "graph": {"nodes": [{"id": "n1", "type": "llm"}], "edges": []},
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 200, r.text
    assert (tmp_path / "agent.py").read_text() == payload["code"]
    sidecar = (tmp_path / ".apx-builder.json").read_text()
    assert "nodes" in sidecar
    assert "n1" in sidecar


def test_save_writes_to_target_relative_path(tmp_path, monkeypatch, app):
    """If `target` is passed, write there instead of cwd/agent.py."""
    monkeypatch.chdir(tmp_path)
    nested = tmp_path / "examples" / "demo"
    nested.mkdir(parents=True)
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nfrom apx_agent import Agent\n",
        "graph": {"nodes": [], "edges": []},
        "target": "examples/demo/agent.py",
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 200, r.text
    assert (nested / "agent.py").exists()
    assert (nested / ".apx-builder.json").exists()


def test_save_rejects_absolute_paths(tmp_path, monkeypatch, app):
    """Saving to an absolute path is rejected — only paths under cwd allowed."""
    monkeypatch.chdir(tmp_path)
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\n",
        "graph": {},
        "target": "/etc/passwd",
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 400
    assert not (tmp_path / "etc" / "passwd").exists()


def test_save_rejects_parent_escape(tmp_path, monkeypatch, app):
    """Saving to ../foo is rejected — no escaping the cwd."""
    monkeypatch.chdir(tmp_path)
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\n",
        "graph": {},
        "target": "../foo/agent.py",
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 400


def test_save_atomic_via_tmp_rename(tmp_path, monkeypatch, app):
    """Successful save leaves no .tmp files behind."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "agent.py").write_text("# Generated by apx-agent visual builder\nold\n")
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nnew\n",
        "graph": {"nodes": [], "edges": []},
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 200, r.text
    assert (tmp_path / "agent.py").read_text() == payload["code"]
    # No stale .tmp files
    tmps = list(tmp_path.glob("*.tmp"))
    assert tmps == [], f"unexpected leftover tmp files: {tmps}"


def test_save_refuses_to_clobber_hand_written_file(tmp_path, monkeypatch, app):
    """POSTing /save when agent.py exists WITHOUT the sentinel returns 409."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "agent.py").write_text("# Hand-written\nfrom apx_agent import Agent\n")
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nnew\n",
        "graph": {"nodes": [], "edges": []},
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 409
    # Hand-written file untouched
    assert "Hand-written" in (tmp_path / "agent.py").read_text()


def test_save_force_flag_overrides_clobber_check(tmp_path, monkeypatch, app):
    """POSTing /save?force=1 overwrites a hand-written file."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "agent.py").write_text("# Hand-written\nfrom apx_agent import Agent\n")
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nnew\n",
        "graph": {"nodes": [], "edges": []},
    }
    r = client.post("/_apx/builder/save?force=1", json=payload)
    assert r.status_code == 200
    assert "new" in (tmp_path / "agent.py").read_text()
    assert "Hand-written" not in (tmp_path / "agent.py").read_text()


def test_save_overwrites_canvas_generated_file_without_force(tmp_path, monkeypatch, app):
    """A previously-canvas-saved agent.py (with sentinel) can be overwritten with no force."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "agent.py").write_text(
        "# Generated by apx-agent visual builder\nold\n"
    )
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nnew\n",
        "graph": {"nodes": [], "edges": []},
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 200
    assert "new" in (tmp_path / "agent.py").read_text()


def test_list_uc_functions(tmp_path, monkeypatch, app):
    """GET /uc-functions returns a list of UC functions in the requested schema."""
    from unittest.mock import MagicMock
    from databricks.sdk import WorkspaceClient

    fake_ws = MagicMock(spec=WorkspaceClient)
    fake_func1 = MagicMock(
        full_name="main.tools.classify_intent",
        name="classify_intent",
        comment="Classify a customer query.",
        input_params=MagicMock(parameters=[
            MagicMock(name="query", type_text="STRING"),
        ]),
    )
    fake_func2 = MagicMock(
        full_name="main.tools.score_customer",
        name="score_customer",
        comment="Score a customer.",
        input_params=None,
    )
    fake_ws.functions.list.return_value = iter([fake_func1, fake_func2])

    # Patch the ws resolver
    monkeypatch.setattr(
        "apx_agent._builder_routes._resolve_workspace_client",
        lambda request: fake_ws,
    )

    client = TestClient(app)
    r = client.get("/_apx/builder/uc-functions?catalog=main&schema=tools")
    assert r.status_code == 200, r.text
    data = r.json()
    assert "functions" in data
    assert len(data["functions"]) == 2
    assert data["functions"][0]["full_name"] == "main.tools.classify_intent"
    assert data["functions"][0]["comment"] == "Classify a customer query."


def test_list_uc_functions_handles_errors(tmp_path, monkeypatch, app):
    """If ws.functions.list raises, the endpoint returns 502 with detail."""
    from unittest.mock import MagicMock
    fake_ws = MagicMock()
    fake_ws.functions.list.side_effect = RuntimeError("permission denied")
    monkeypatch.setattr(
        "apx_agent._builder_routes._resolve_workspace_client",
        lambda request: fake_ws,
    )
    client = TestClient(app)
    r = client.get("/_apx/builder/uc-functions?catalog=main&schema=tools")
    assert r.status_code == 502
    assert "permission denied" in r.json()["detail"]


def test_list_vector_indexes(tmp_path, monkeypatch, app):
    """GET /vector-indexes returns a list of VS indexes."""
    from unittest.mock import MagicMock
    fake_ws = MagicMock()
    fake_idx = MagicMock(name="docs", index_type="DELTA_SYNC")
    fake_idx.name = "main.search.docs"
    fake_endpoint = MagicMock(name="vs-endpoint")
    fake_endpoint.name = "vs-endpoint"
    fake_ws.vector_search_endpoints.list_endpoints.return_value = iter([fake_endpoint])
    fake_ws.vector_search_indexes.list_indexes.return_value = MagicMock(
        vector_indexes=[fake_idx]
    )
    monkeypatch.setattr(
        "apx_agent._builder_routes._resolve_workspace_client",
        lambda request: fake_ws,
    )
    client = TestClient(app)
    r = client.get("/_apx/builder/vector-indexes")
    assert r.status_code == 200, r.text
    data = r.json()
    assert "indexes" in data


def test_list_genie_spaces(tmp_path, monkeypatch, app):
    """GET /genie-spaces returns a list of Genie spaces."""
    from unittest.mock import MagicMock
    fake_ws = MagicMock()
    fake_space1 = MagicMock(
        space_id="abc123",
        title="Sales Genie",
        description="Answer sales questions.",
    )
    fake_space2 = MagicMock(
        space_id="def456",
        title="Support Genie",
        description="Answer support questions.",
    )
    fake_ws.genie.list_spaces.return_value = MagicMock(spaces=[fake_space1, fake_space2])
    monkeypatch.setattr(
        "apx_agent._builder_routes._resolve_workspace_client",
        lambda request: fake_ws,
    )
    client = TestClient(app)
    r = client.get("/_apx/builder/genie-spaces")
    assert r.status_code == 200, r.text
    data = r.json()
    assert "spaces" in data
    assert len(data["spaces"]) == 2
    assert data["spaces"][0]["space_id"] == "abc123"
    assert data["spaces"][0]["title"] == "Sales Genie"


def test_state_reports_drift_when_agent_py_newer(tmp_path, monkeypatch, app):
    """If agent.py mtime > sidecar mtime, state returns drift=True."""
    monkeypatch.chdir(tmp_path)
    import time
    (tmp_path / ".apx-builder.json").write_text('{"nodes":[],"edges":[]}')
    time.sleep(0.05)  # ensure mtime gap
    (tmp_path / "agent.py").write_text("# Generated by apx-agent visual builder\nfrom apx_agent import Agent\n")
    client = TestClient(app)
    r = client.get("/_apx/builder/state")
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["drift"] is True
    assert body["agent_py_exists"] is True
    assert body["sidecar_exists"] is True


def test_state_no_drift_when_sidecar_fresher(tmp_path, monkeypatch, app):
    monkeypatch.chdir(tmp_path)
    import time
    (tmp_path / "agent.py").write_text("# Generated by apx-agent visual builder\n")
    time.sleep(0.05)
    (tmp_path / ".apx-builder.json").write_text('{"nodes":[],"edges":[]}')
    client = TestClient(app)
    r = client.get("/_apx/builder/state")
    assert r.status_code == 200, r.text
    assert r.json()["drift"] is False


def test_state_reports_identity_from_pyproject(tmp_path, monkeypatch, app):
    """Identity (name + profile) is sourced from [tool.apx.agent] in pyproject.toml."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "demo"\nversion = "0.1.0"\n'
        '[tool.apx.agent]\nname = "mcp-demo-agent"\nprofile = "fe-stable"\n'
    )
    client = TestClient(app)
    r = client.get("/_apx/builder/state")
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["identity"]["name"] == "mcp-demo-agent"
    assert body["identity"]["profile"] == "fe-stable"


def test_state_handles_missing_pyproject(tmp_path, monkeypatch, app):
    """When pyproject.toml is missing, identity is None (canvas shows 'Untitled')."""
    monkeypatch.chdir(tmp_path)
    client = TestClient(app)
    r = client.get("/_apx/builder/state")
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["identity"] is None or body["identity"] == {}
    assert body["drift"] is False  # neither file exists → no drift
