"""Tests for the /_apx/builder SPA static-asset routes."""
from __future__ import annotations

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from apx_agent._builder_routes import build_builder_router


@pytest.fixture
def app(tmp_path, monkeypatch):
    # Stage a minimal _builder_ui_dist with one HTML and one JS asset
    dist_root = tmp_path / "_builder_ui_dist"
    (dist_root / "assets").mkdir(parents=True)
    (dist_root / "index.html").write_text(
        "<!doctype html><html><body><div id='root'></div>"
        "<script src='/_apx/builder/assets/main.js'></script>"
        "</body></html>"
    )
    (dist_root / "assets" / "main.js").write_text("console.log('builder');")

    # Patch the dist-locator to point at our tmp tree
    monkeypatch.setattr(
        "apx_agent._builder_routes._dist_root",
        lambda: dist_root,
    )
    app = FastAPI()
    app.include_router(build_builder_router())
    return app


def test_index_served(app):
    client = TestClient(app)
    r = client.get("/_apx/builder/")
    assert r.status_code == 200
    assert "text/html" in r.headers["content-type"]
    assert "id='root'" in r.text


def test_asset_served(app):
    client = TestClient(app)
    r = client.get("/_apx/builder/assets/main.js")
    assert r.status_code == 200
    assert "javascript" in r.headers["content-type"]
    assert "console.log" in r.text


def test_spa_fallback(app):
    """Deep links like /_apx/builder/some/canvas-route fall back to index.html."""
    client = TestClient(app)
    r = client.get("/_apx/builder/some/canvas-route")
    assert r.status_code == 200
    assert "text/html" in r.headers["content-type"]
    assert "id='root'" in r.text


def test_save_writes_agent_py_and_sidecar(tmp_path, monkeypatch, app):
    """POST /save writes agent.py + .apx-builder.json in the cwd."""
    monkeypatch.chdir(tmp_path)
    client = TestClient(app)
    payload = {
        "code": (
            "# Generated by apx-agent visual builder\n"
            "from apx_agent import Agent\n"
            "agent = Agent(instructions='hi', tools=[])\n"
        ),
        "graph": {"nodes": [{"id": "n1", "type": "llm"}], "edges": []},
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 200, r.text
    assert (tmp_path / "agent.py").read_text() == payload["code"]
    sidecar = (tmp_path / ".apx-builder.json").read_text()
    assert "nodes" in sidecar
    assert "n1" in sidecar


def test_save_writes_to_target_relative_path(tmp_path, monkeypatch, app):
    """If `target` is passed, write there instead of cwd/agent.py."""
    monkeypatch.chdir(tmp_path)
    nested = tmp_path / "examples" / "demo"
    nested.mkdir(parents=True)
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nfrom apx_agent import Agent\n",
        "graph": {"nodes": [], "edges": []},
        "target": "examples/demo/agent.py",
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 200, r.text
    assert (nested / "agent.py").exists()
    assert (nested / ".apx-builder.json").exists()


def test_save_rejects_absolute_paths(tmp_path, monkeypatch, app):
    """Saving to an absolute path is rejected — only paths under cwd allowed."""
    monkeypatch.chdir(tmp_path)
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\n",
        "graph": {},
        "target": "/etc/passwd",
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 400
    assert not (tmp_path / "etc" / "passwd").exists()


def test_save_rejects_parent_escape(tmp_path, monkeypatch, app):
    """Saving to ../foo is rejected — no escaping the cwd."""
    monkeypatch.chdir(tmp_path)
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\n",
        "graph": {},
        "target": "../foo/agent.py",
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 400


def test_save_atomic_via_tmp_rename(tmp_path, monkeypatch, app):
    """Successful save leaves no .tmp files behind."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "agent.py").write_text("# Generated by apx-agent visual builder\nold\n")
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nnew\n",
        "graph": {"nodes": [], "edges": []},
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 200, r.text
    assert (tmp_path / "agent.py").read_text() == payload["code"]
    # No stale .tmp files
    tmps = list(tmp_path.glob("*.tmp"))
    assert tmps == [], f"unexpected leftover tmp files: {tmps}"


def test_save_refuses_to_clobber_hand_written_file(tmp_path, monkeypatch, app):
    """POSTing /save when agent.py exists WITHOUT the sentinel returns 409."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "agent.py").write_text("# Hand-written\nfrom apx_agent import Agent\n")
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nnew\n",
        "graph": {"nodes": [], "edges": []},
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 409
    # Hand-written file untouched
    assert "Hand-written" in (tmp_path / "agent.py").read_text()


def test_save_force_flag_overrides_clobber_check(tmp_path, monkeypatch, app):
    """POSTing /save?force=1 overwrites a hand-written file."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "agent.py").write_text("# Hand-written\nfrom apx_agent import Agent\n")
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nnew\n",
        "graph": {"nodes": [], "edges": []},
    }
    r = client.post("/_apx/builder/save?force=1", json=payload)
    assert r.status_code == 200
    assert "new" in (tmp_path / "agent.py").read_text()
    assert "Hand-written" not in (tmp_path / "agent.py").read_text()


def test_save_overwrites_canvas_generated_file_without_force(tmp_path, monkeypatch, app):
    """A previously-canvas-saved agent.py (with sentinel) can be overwritten with no force."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / "agent.py").write_text(
        "# Generated by apx-agent visual builder\nold\n"
    )
    client = TestClient(app)
    payload = {
        "code": "# Generated by apx-agent visual builder\nnew\n",
        "graph": {"nodes": [], "edges": []},
    }
    r = client.post("/_apx/builder/save", json=payload)
    assert r.status_code == 200
    assert "new" in (tmp_path / "agent.py").read_text()
