"""FastAPI entry point for Databricks Apps — AUTO-GENERATED by apx-agent scaffold.

Don't edit this file. Edit ``../agent.py`` (or the deeper backend module
it re-exports) to change the agent.

This file is the framework boilerplate:
  * Imports ``agent`` from the top-level ``agent.py``.
  * Compiles it to the MLflow ResponsesAgent contract.
  * Registers ``@invoke`` / ``@stream`` handlers.
  * Mounts apx-agent's ``/mcp`` + ``/.well-known/agent.json`` + ``/health``
    + ``/readyz`` so the deploy gate and Genie / Genie Code can consume it.

Driven by the ``uvicorn`` command in ``databricks.yml`` at deploy time.
"""

from __future__ import annotations

import os

from mlflow.genai.agent_server import AgentServer, invoke, stream

from apx_agent import compile_to_responses_agent, mount_mcp_endpoints, mount_readyz

from agent import agent

# Keep this fallback aligned with databricks.yml's llm_endpoint_name default.
DEFAULT_MODEL = "databricks-claude-sonnet-4-6"
MODEL = os.environ.get("APX_MODEL", DEFAULT_MODEL)

_invoke_fn, _stream_fn = compile_to_responses_agent(agent, model=MODEL)


@invoke()
def non_streaming(request):
    """Non-streaming request handler — POST /invocations."""
    return _invoke_fn(request)


@stream()
def streaming(request):
    """Streaming request handler — POST /invocations with stream=true."""
    yield from _stream_fn(request)


server = AgentServer(agent_type="ResponsesAgent")
app = server.app

mount_mcp_endpoints(app, agent)
mount_readyz(app, agent, model=MODEL)

# Dev UI (/_apx/* including Discover) is mounted by mount_mcp_endpoints for
# both local and Apps runtimes. Writes on Apps still require APX_DEV_UI_TOKEN.


if __name__ == "__main__":
    server.run("agent_server.start_server:app")
